# .streamlit/secrets.toml
OPENAI_API_KEY = "your-api-key-here"
CLAUDE_API_KEY = "your-claude-api-key-here"
GROQ_API_KEY = “your-groq-api-key-here”

TRUBRICS_EMAIL = "your-trubrics-email-here"
TRUBRICS_PASSWORD = "your-trubrics-pswd-here"