# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
CLAUDE_API_KEY = "your-claude-api-key-here"

TRUBRICS_EMAIL = "lexbudgettest@gmail.com"
TRUBRICS_PASSWORD = "L3xBudg3tAsst!"